import requests
import socket
import ssl
import datetime
import certifi
from urllib.parse import urlparse
from fpdf import FPDF

# --- CONFIGURATION (Customize for the Agency) ---
AGENCY_NAME = "CyberSecure India"
AGENCY_TAGLINE = "Enterprise-Grade Security Audits"
AGENCY_WEBSITE = "www.cybersecure-india.com"

# --- COLORS (RGB) ---
COLOR_PRIMARY = (41, 128, 185)    # Corporate Blue
COLOR_SECONDARY = (52, 73, 94)    # Dark Grey
COLOR_DANGER = (192, 57, 43)      # Deep Red
COLOR_SUCCESS = (39, 174, 96)     # Emerald Green
COLOR_LIGHT_GRAY = (245, 245, 245) # Background Gray

class ProfessionalPDF(FPDF):
    def header(self):
        # 1. Dark Header Background
        self.set_fill_color(*COLOR_SECONDARY)
        self.rect(0, 0, 210, 40, 'F')
        
        # 2. Agency Name (White)
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 24)
        self.set_xy(10, 10)
        self.cell(0, 10, AGENCY_NAME, 0, 1, 'L')
        
        # 3. Tagline (Light Gray)
        self.set_font('Arial', 'I', 10)
        self.set_text_color(200, 200, 200)
        self.set_xy(10, 20)
        self.cell(0, 10, AGENCY_TAGLINE, 0, 1, 'L')
        
        # 4. "CONFIDENTIAL" Stamp on the right
        self.set_font('Arial', 'B', 12)
        self.set_text_color(255, 100, 100) # Light Red
        self.set_xy(150, 15)
        self.cell(50, 10, "[ CONFIDENTIAL ]", 0, 0, 'R')
        
        self.ln(25) # Space after header

    def footer(self):
        self.set_y(-20)
        # Draw a line
        self.set_draw_color(200, 200, 200)
        self.line(10, 275, 200, 275)
        
        self.set_font('Arial', '', 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, f'Generated by {AGENCY_NAME} Automated Scanner', 0, 1, 'C')
        self.cell(0, 5, f'Visit {AGENCY_WEBSITE} for full remediation services.', 0, 0, 'C')

    def chapter_title(self, label, color):
        # Section Title with colored underline
        self.set_font('Arial', 'B', 16)
        self.set_text_color(*color)
        self.cell(0, 10, label, 0, 1, 'L')
        
        # Underline bar
        self.set_fill_color(*color)
        self.rect(10, self.get_y(), 190, 1, 'F')
        self.ln(5)

    def add_bullet(self, text, type='danger'):
        # Choose icon color
        if type == 'danger':
            self.set_fill_color(*COLOR_DANGER) # Red Square
            self.set_text_color(*COLOR_DANGER)
            prefix = "CRITICAL ISSUE"
        else:
            self.set_fill_color(*COLOR_SUCCESS) # Green Square
            self.set_text_color(*COLOR_SUCCESS)
            prefix = "PASSED"

        # Draw the Bullet (Small Square)
        y = self.get_y()
        self.rect(10, y+2, 4, 4, 'F') 
        
        # Title of the bullet
        self.set_xy(16, y)
        self.set_font('Arial', 'B', 10)
        self.cell(30, 8, prefix, 0, 0)
        
        # The Description text
        self.set_text_color(50, 50, 50) # Dark Gray for text
        self.set_font('Arial', '', 10)
        self.set_xy(45, y)
        self.multi_cell(0, 8, text)
        self.ln(2) # Spacing between items

    def add_score_card(self, issues_count, passed_count):
        # A gray box for the summary
        self.set_fill_color(*COLOR_LIGHT_GRAY)
        self.rect(10, self.get_y(), 190, 30, 'F')
        
        start_y = self.get_y() + 5
        
        # Text Summary
        self.set_xy(15, start_y)
        self.set_font('Arial', 'B', 12)
        self.set_text_color(50, 50, 50)
        self.cell(100, 10, "Executive Summary", 0, 1)
        
        self.set_font('Arial', '', 10)
        self.set_xy(15, start_y + 8)
        self.cell(100, 10, f"This automated audit scanned for common vulnerabilities.", 0, 1)
        
        # Big Score Numbers (Right Side)
        self.set_xy(140, start_y)
        self.set_font('Arial', 'B', 24)
        
        if issues_count > 0:
            self.set_text_color(*COLOR_DANGER)
            self.cell(50, 10, f"{issues_count} ISSUES", 0, 1, 'R')
            self.set_font('Arial', 'B', 10)
            self.set_xy(140, start_y + 10)
            self.cell(50, 5, "Requires Immediate Action", 0, 1, 'R')
        else:
            self.set_text_color(*COLOR_SUCCESS)
            self.cell(50, 10, "SECURE", 0, 1, 'R')
            
        self.ln(20)

class SimpleSecurityScanner:
    def __init__(self, target_url):
        if not target_url.startswith(("http://", "https://")):
            self.target_url = "https://" + target_url
        else:
            self.target_url = target_url
            
        self.parsed_url = urlparse(self.target_url)
        self.hostname = self.parsed_url.netloc
        self.report = {"target": self.target_url, "issues": [], "good_practices": []}

    def check_ssl(self):
        print(f"[*] Checking SSL for {self.hostname}...")
        try:
            context = ssl.create_default_context(cafile=certifi.where())
            with socket.create_connection((self.hostname, 443), timeout=5) as sock:
                with context.wrap_socket(sock, server_hostname=self.hostname) as ssock:
                    cert = ssock.getpeercert()
                    not_after_str = cert['notAfter']
                    not_after = datetime.datetime.strptime(not_after_str, '%b %d %H:%M:%S %Y %Z')
                    current_time = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
                    days_left = (not_after - current_time).days
                    
                    if days_left < 0:
                        self.report["issues"].append(f"SSL Certificate expired on {not_after.strftime('%Y-%m-%d')}.")
                    elif days_left < 15:
                        self.report["issues"].append(f"SSL Certificate expires soon ({days_left} days left).")
                    else:
                        self.report["good_practices"].append(f"SSL Certificate is valid (Expires in {days_left} days).")
        except Exception as e:
            self.report["issues"].append(f"SSL Connection failed. Error: {str(e)}")

    def check_headers(self):
        print(f"[*] Fetching headers from {self.target_url}...")
        try:
            response = requests.get(self.target_url, timeout=10, verify=certifi.where())
            headers = response.headers
            security_headers = {
                "X-Frame-Options": "Protects against Clickjacking attacks.",
                "Content-Security-Policy": "Mitigates XSS and data injection attacks.",
                "Strict-Transport-Security": "Enforces secure (HTTPS) connections.",
                "X-Content-Type-Options": "Prevents MIME-sniffing attacks."
            }
            for header, purpose in security_headers.items():
                if header in headers:
                    self.report["good_practices"].append(f"Header '{header}' is present.")
                else:
                    self.report["issues"].append(f"Missing header '{header}' ({purpose})")
            if "Server" in headers:
                self.report["issues"].append(f"Server header is exposed: '{headers['Server']}'.")
        except requests.exceptions.RequestException as e:
            self.report["issues"].append(f"Could not fetch URL. Error: {str(e)}")

    def basic_tech_detect(self):
        print(f"[*] Checking for exposed technologies...")
        try:
            response = requests.get(self.target_url, timeout=5, verify=certifi.where())
            if "wp-content" in response.text or "wp-includes" in response.text:
                self.report["issues"].append("Site appears to be using WordPress (Verify version is up to date).")
        except:
            pass 

    def generate_pdf(self):
        pdf = ProfessionalPDF()
        pdf.add_page()
        
        # Meta Info
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(30, 10, "Target:", 0, 0)
        pdf.set_font("Arial", '', 12)
        pdf.cell(0, 10, self.hostname, 0, 1)
        
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(30, 10, "Date:", 0, 0)
        pdf.set_font("Arial", '', 12)
        pdf.cell(0, 10, datetime.datetime.now().strftime('%Y-%m-%d %H:%M'), 0, 1)
        pdf.ln(5)

        # Score Card
        pdf.add_score_card(len(self.report["issues"]), len(self.report["good_practices"]))

        # Section 1: Vulnerabilities
        pdf.chapter_title("Security Vulnerabilities Found", COLOR_DANGER)
        
        if not self.report["issues"]:
            pdf.set_font("Arial", 'I', 11)
            pdf.cell(0, 10, "No critical issues detected during this scan.", 0, 1)
        else:
            for issue in self.report["issues"]:
                pdf.add_bullet(issue, type='danger')

        pdf.ln(10)

        # Section 2: Good Practices
        pdf.chapter_title("Good Practices Observed", COLOR_SUCCESS)
        
        for good in self.report["good_practices"]:
            pdf.add_bullet(good, type='success')

        # Save
        filename = f"Audit_Report_{self.hostname}.pdf"
        pdf.output(filename)
        print(f"\n✅ SUCCESS! Professional PDF Report generated: {filename}")

    def run(self):
        self.check_ssl()
        self.check_headers()
        self.basic_tech_detect()
        self.generate_pdf()

if __name__ == "__main__":
    target = input("Enter website URL to scan (e.g., example.com): ")
    scanner = SimpleSecurityScanner(target)
    scanner.run()